In [16]:
import tensorflow as tf
import pandas as pd

In [17]:
import numpy as np

In [18]:
from tensorflow import keras
from tensorflow.keras import layers

In [19]:
cols = list(pd.read_csv("C:\\Users\\hp\Desktop\\Transfer\\AGV\\Second set of tasks\\train.csv", nrows =1))
x_train = pd.read_csv("C:\\Users\\hp\Desktop\\Transfer\\AGV\\Second set of tasks\\train.csv", usecols =[i for i in cols if i != 'label'])
y_train = pd.read_csv("C:\\Users\\hp\Desktop\\Transfer\\AGV\Second set of tasks\\train.csv")['label']
x_test = pd.read_csv("C:\\Users\\hp\Desktop\\Transfer\\AGV\\Second set of tasks\\test(1).csv",index_col=0)
print(x_test.shape)


(28000, 784)


In [20]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(512, activation='relu', input_shape=(784,)),
  tf.keras.layers.Dense(128),
  tf.keras.layers.Dense(128),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [21]:
predictions = model(np.array(x_train)).numpy()
predictions

array([[-101.10044 ,   62.386642,  101.987564, ...,  -21.699099,
         -99.64036 ,  -96.91901 ],
       [ -23.4985  ,  169.96739 ,  163.29407 , ..., -155.30786 ,
         -40.697556, -160.26509 ],
       [ 131.2916  ,  -50.854176,   65.97063 , ...,  -24.873701,
        -195.50047 ,  107.20521 ],
       ...,
       [  33.023544,  220.76936 ,   -4.211732, ..., -217.80467 ,
         -42.100372,  100.13049 ],
       [  45.04179 ,   37.81772 ,  175.79907 , ..., -143.35573 ,
        -248.93771 ,  120.382645],
       [ -63.09305 ,  127.847916,   37.684204, ...,  -43.35294 ,
         -69.051506,  -27.999804]], dtype=float32)

In [22]:
tf.nn.softmax(predictions).numpy()

array([[0.0000000e+00, 6.3319596e-18, 9.9999976e-01, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [1.9977848e-16, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 6.9177277e-27],
       ...,
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 1.9194057e-30, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 2.1922688e-26, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [23]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [24]:
loss_fn(y_train, predictions).numpy()

247.51811

In [25]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [26]:
model.fit(np.array(x_train), np.array(y_train), epochs = 10)

Epoch 1/10
1313/1313 [==============================] - 4s 3ms/step - loss: 4.3827 - accuracy: 0.8584
Epoch 2/10
1313/1313 [==============================] - 4s 3ms/step - loss: 0.5941 - accuracy: 0.8937
Epoch 3/10
1313/1313 [==============================] - 4s 3ms/step - loss: 0.5042 - accuracy: 0.9064
Epoch 4/10
1313/1313 [==============================] - 4s 3ms/step - loss: 0.4049 - accuracy: 0.9196
Epoch 5/10
1313/1313 [==============================] - 5s 4ms/step - loss: 0.3441 - accuracy: 0.9295
Epoch 6/10
1313/1313 [==============================] - 5s 4ms/step - loss: 0.2740 - accuracy: 0.9410
Epoch 7/10
1313/1313 [==============================] - 5s 3ms/step - loss: 0.2349 - accuracy: 0.9460
Epoch 8/10
1313/1313 [==============================] - 5s 4ms/step - loss: 0.1993 - accuracy: 0.9545
Epoch 9/10
1313/1313 [==============================] - 5s 3ms/step - loss: 0.1900 - accuracy: 0.9566
Epoch 10/10
1313/1313 [==============================] - 5s 3ms/step - loss: 0.181

In [27]:
ans = model.predict(x_test,  verbose='auto')

875/875 [==============================] - 1s 1ms/step


In [28]:
pred_list = np.zeros(28000)
for i in range(28000):
    pred_list[i] = np.argmax(ans[i])

In [29]:
pred_list

array([2., 0., 9., ..., 3., 9., 2.])

In [30]:
result = "Result.csv"
df=pd.DataFrame(pred_list)
df.to_csv(result)